site_name: GDF Saúde - Grupo 9


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


nav:
  - Home: index.md

  - Atas:
      - 28/03/2025: atas/ata_28_03.md
      - 04/04/2025: atas/ata_04_04.md
      - 11/04/2025: atas/ata_11_04.md
      - 21/04/2025: atas/ata_21_04.md
      - 09/05/2025: atas/ata_09_05.md
      - 16/05/2025: atas/ata_16_05.md
      - 30/05/2025: atas/ata_30_05.md
      - 06/05/2025: atas/ata_06_06.md

  - Videos:
      - Vídeos: videos/videos.md
  - Apresentação:
      - Entrega 1: apresentacao/apresentcao1.md
      - Entrega 2: apresentacao/apresentacao2.md
      - Entrega 3: apresentacao/apresentacao3.md
      - Entrega 4: apresentacao/apresentacao4.md
      - Entrega 5: apresentacao/apresentacao5.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Responsabilidades da equipe: planejamento/Definição_de_Equipe_e_Responsabilidades.md
      - Ferramentas: planejamento/ferramentas.md 
      - Cronograma planejado: planejamento/Cronograma.md
      - Cronograma executado: planejamento/Cronograma_execudato.md
      - Aplicativo: planejamento/aplicativo.md
      - Aplicativos Avaliados: planejamento/aplicativos-avaliados.md

  - Pré-rastreabilidade:
      - Rich Picture: pre-rastreabilidade/rich_picture.md

  - Elicitação: 
      - Requisios Elicitados Finais: elicitacao/requisitos_finais.md
      - Requisios Elicitados: elicitacao/elicitacao.md   
      - Perfil de Usuário: elicitacao/perfil.md
      - Personas: elicitacao/personas.md

      - Técnicas de Priorização: 
          - $100: elicitacao/priorizacao/dolares100.md
          - First Thing First: elicitacao/priorizacao/first_thing_first.md
          - Moscow: elicitacao/priorizacao/moscow.md
          - Three Level Scale: elicitacao/priorizacao/threeLevelScale.md

      - Técnicas de Elicitação:
          - Introspecção: elicitacao/tecnicas/introspeccao.md
          - Entrevista: elicitacao/tecnicas/entrevista.md
          - Grupo Focal: elicitacao/tecnicas/grupo_focal.md
          - Questionário: elicitacao/tecnicas/questionario.md
          - Glossário: elicitacao/tecnicas/glossario.md
          

  - Modelagem:
      - Metodologias Tradicionais:  
          - Casos de uso: modelagem/tradicional_final/casos_de_usos.md
          - Validação dos Casos de Uso: modelagem/tradicional_final/validacao_caso_uso.md
          - Cenários: modelagem/tradicional_final/cenarios.md
          - Especificação Suplementar: modelagem/tradicional_final/especificacao-suplementar.md
          - Léxicos: modelagem/tradicional_final/lexicos.md  
      - Metodologias Ágeis: 
          - Histórias de Usuário: modelagem/metodos_ageis/historias_todos02.md
          - Backlog do Produto: modelagem/metodos_ageis/backlog.md
          - NFR framework: modelagem/metodos_ageis/nfr.md 
      - Metodologias Tradicionais Versões Antigas: 
          - Casos de uso: modelagem/metodos_tradicionais/casos_de_usos.md
          - Validação dos Casos de Uso: modelagem/metodos_tradicionais/validacao_caso_uso.md
          - Cenários: modelagem/metodos_tradicionais/cenarios.md
          - Especificação Suplementar: modelagem/metodos_tradicionais/especificacao-suplementar.md
          - Léxicos: modelagem/metodos_tradicionais/lexicos.md  

  - Pós rastreabilidade:
      - Matriz de Rastreabilidade: pos-rastreabilidade/matriz_geral.md
      - Backward From: pos-rastreabilidade/backward_from.md
      - Forward From: pos-rastreabilidade/forward_from.md

  - Verificação:
      - Grupo:
          - Entrega 1: verificacao/lista_de_VerificacaoEntrega1.md
          - Entrega 2: verificacao/lista_de_VerificacaoEntrega2.md
          - Entrega 3: verificacao/lista_de_verificacaoEntrega3.md
          - Entrega 4: verificacao/lista_de_verificacaoEntrega4.md
          - Entrega 6: verificacao/lista_de_VerificacaoEntrega6.md
      - Grupo +1:
          - Entrega 1: verificacao/lista_de_VerificacaoEntrega1.md
          - Entrega 2: verificacao/lista_de_VerificacaoEntrega2.md
          - Entrega 3: verificacao/lista_de_verificacaoEntrega3.md
          - Entrega 4: verificacao/lista_de_verificacaoEntrega4.md
          - Entrega 6: verificacao/lista_de_VerificacaoEntrega6.md

  - Inspeção:
      - Grupo -1 e professor: inspecao/grupo-1eprofessor.md
      - Grupo:
          - Entrega 1: inspecao/lista_de_inspecaoEntrega1.md
          - Entrega 2: inspecao/inspecao_2_grupo.md
          - Entrega 3: inspecao/inspecao_3_grupo.md
          - Entrega 4: inspecao/inspecao_4_grupo.md
          - Entrega 6: inspecao/inspecao_6_grupo.md
      - Grupo +1:
          - Entrega 1: inspecao/lista_de_inspecaoEntrega1Grupo+1.md
          - Entrega 2: inspecao/inspecao_2_grupo+1.md
          - Entrega 3: inspecao/inspecao_3_grupo+1.md
          - Entrega 4: inspecao/inspecao_4_grupo+1.md
          - Entrega 6: inspecao/inspecao_6_grupo+1.md
    
  - Validação:
      - Protótipos: modelagem/prototipos.md
          
extra_css:
  - stylesheets/extra.css
