site_name: SINESP - Grupo 9


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


nav:
  - Home: index.md
  - Atas:
      - 28/03/2025: atas/ata_28_03.md
      - 04/04/2025: atas/ata_04_04.md
      - 11/04/2025: atas/ata_11_04.md
  - Videos:
      - videos: videos/videos.md
  - Planejamento:
      - Ferramentas: planejamento/ferramentas.md 
      - Cronograma: planejamento/Cronograma.md


extra_css:
  - stylesheets/extra.css
